name: inkdrop
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: Note-taking App with Robust Markdown Editor
description: |
  Inkdrop enables hackers to keep track of their daily progress when it comes to hacking in one convenient spot without having to rely on traditional word processors.
  Inkdrop features support for Markdown with the ability to do code syntax highlighting as well as built-in syncing capabilities.
  You can organize your progress in a clean, uniform way that's focused on ensuring that the information is easy to work through and can be read uniformly.

grade: stable
confinement: devmode # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64

parts:
  inkdrop:
    install: |
      DEB_API="https://api.inkdrop.app/download/linux/deb"
      DEB_URL=$(curl -w "%{url_effective}\n" -I -L -s -S "${DEB_API}" -o /dev/null)
      VERSION=$(echo "${DEB_URL}" | cut -d'/' -f4 | tr -d 'v')
      echo $VERSION > $SNAPCRAFT_STAGE/version
    plugin: dump
    source: https://api.inkdrop.app/download/linux/deb
    source-type: deb
    # Correct path to icon.
    prepare: |
      sed -i 's|Icon=inkdrop|Icon=/usr/share/pixmaps/inkdrop\.png|g' usr/share/applications/inkdrop.desktop
    build-packages:
      - curl
    stage-packages:
      - libsecret-1-0
      - libcanberra-gtk-module
      - libgnome-keyring0
      - libgtk-3-0

apps:
  inkdrop:
    command: bin/desktop-launch $SNAP/usr/share/inkdrop/inkdrop
    desktop: usr/share/applications/inkdrop.desktop
  ipm:
    command: bin/desktop-launch $SNAP/usr/bin/ipm
