name: inkdrop
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: Note-taking App with Robust Markdown Editor
description: |
  Inkdrop enables hackers to keep track of their daily progress when it comes to hacking in one convenient spot without having to rely on traditional word processors.
  Inkdrop features support for Markdown with the ability to do code syntax highlighting as well as built-in syncing capabilities.
  You can organize your progress in a clean, uniform way that's focused on ensuring that the information is easy to work through and can be read uniformly.

grade: stable
confinement: strict

architectures:
  - build-on: amd64

parts:
  inkdrop:
    plugin: dump
    # source: /home/nora/Developments/inkdrop-desktop/dist/inkdrop_3.25.2_amd64.deb
    source: https://api.inkdrop.app/download/linux/deb?pre=1
    source-type: deb
    override-build: |
      snapcraftctl build
      DEB_API="https://api.inkdrop.app/download/linux/deb"
      DEB_URL=$(curl -w "%{url_effective}\n" -I -L -s -S "${DEB_API}" -o /dev/null)
      VERSION=$(echo "${DEB_URL}" | cut -d'/' -f4 | tr -d 'v')
      echo $VERSION > $SNAPCRAFT_STAGE/version
      # echo 3.25.2 > $SNAPCRAFT_STAGE/version
      # Correct path to icon.
      sed -i 's|Icon=inkdrop|Icon=/usr/share/pixmaps/inkdrop\.png|g' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/inkdrop.desktop
    build-packages:
      - curl
    stage-packages:
      - libcanberra-gtk-module
      - libcanberra-gtk3-module
      - libgles2-mesa
      - libgnome-keyring0
      - libsecret-1-0
      - libglu1-mesa
      - libxkbfile1
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpulse0
      - libxss1
      - libxtst6
    after:
      - desktop-gtk3

apps:
  inkdrop:
    command: bin/desktop-launch $SNAP/usr/bin/inkdrop
    desktop: usr/share/applications/inkdrop.desktop
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - browser-support
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - mount-observe
      - network
      - opengl
      - pulseaudio
      - unity7
      - wayland
      - x11
      - password-manager-service
  ipm:
    command: usr/lib/inkdrop/resources/app/ipm/bin/ipm
    plugs:
      - gsettings
      - home
      - mount-observe
      - network
      - password-manager-service
